### ISSUE TITLE
Saving and loading transition matrix in Sparse solver

### ISSUE THREAD

**Issue by MaximeBouton** [JuliaPOMDP/DiscreteValueIteration.jl#24]
It would be useful to be able to load the transition matrix as part of the Sparse Solver interface. 

Suggestions: 
- add a `transition_matrix::Union{Nothing, T}` in the solver fields and just add an if statement that fills in the matrix if it is of type nothing. 
- similarly for the reward matrix
- export a function that would output the transition and reward matrices: `T, R = sparse_mdp(mdp)`

A common use case is to perform reward tuning, we do not want to build the transition matrix every-time we change the reward parameters and re-run the solver.

**Comment by zsunberg** [comment]
Yeah, that makes sense. I like the idea that `solve(solver, mdp)` always solves `mdp`, and putting information about the mdp into the solver object violates that. Maybe it is ok to do that, but I would like to avoid it. This was mentioned on slack before: https://stanford-sisl.slack.com/archives/CB1KETS95/p1541702894059700

Currently, you can override `DiscreteValueIteration.transition_matrix_a_s_sp`, but maybe we need to make something easier to use.

Maybe create a type `SparseTabularMDP` with a constructor that converts an arbitrary mdp and another constructor that just takes in the matrices, or a copy constructor that just allows you to modify certain parts with keywords, e.g.

```julia
spmdp_r1 = SparseTabularMDP(mymdp)
spmdp_r2 = SparseTabularMDP(spmdp_r1, reward=r2)
# ^keeps everything from spmdp_r1 except the reward matrix
# r2 could be another MDP with a different reward function, a function, or the sparse matrix itself

policy_r1 = solve(solver, spmdp_r1)
policy_r2 = solve(solver, spmdp_r2)
```

Not sure if this should go in this package or POMDPModelTools

**Comment by MaximeBouton** [comment]
Eventually `SparseTabularMDP` and `SparseTabularPOMDP` should be in `POMDPModelTools` I think. There is probably a lot of code that would benefit from such representation although we don't have any particular plans of implementing a sparse solver or a sparse belief updater yet.

**Comment by MaximeBouton** [comment]
Actually if we want to be consistent with the existing ` TabularMDP` , the ` SparseTabularMDP` should go in  POMDPModels.

**Comment by MaximeBouton** [comment]
should this be considered resolved by JuliaPOMDP/POMDPModelTools.jl#25 ?
