### ISSUE TITLE
State dependent actions

### ISSUE THREAD

**Issue by etotheipluspi** [JuliaPOMDP/DiscreteValueIteration.jl#4]
Right now, the solver doesn't account for state dependent actions. All actions are assumed to be possible from any given state, and its up to the user to implement any restrictions in the `transition` or `reward` functions (e.g. penalizing impossible actions).  

It may be useful to leverage the `actions(model, state, rng)` function to restrict the solver from iterating over impossible actions. However, this can be tricky to do when the policy is represented by a matrix. One way to do this would be to pre-compute state-to-action mappings and iterate over only actions that are possible. Then assign some large negative reward in the table to all the actions that are not possible.

**Comment by mykelk** [comment]
Wait, should it be done through `actions{S,A}(problem::MDP{S,A}, state::S, aspace::AbstractSpace{A})`?

**Comment by zsunberg** [comment]
This has been implemented
