### ISSUE TITLE
Discrete Value Iteration but based on key-value storage ?

### ISSUE THREAD

**Issue by NeroBlackstone** [JuliaPOMDP/DiscreteValueIteration.jl#53]
If we have this specific MDP:
1. MDP totally generated by generative model, states and actions are unknown before massive sampling.
2. State and action both discrete.
3. State space are nearly infinite, states are hard to enumerate one by one. But number of states are finite after massive sampling in MDP.
4. Actions depend on specific state.

So, apperently, this MDP can't be solved by matrix(or tabular) based solver, since we can't calculate the number of spaces before sampling, which means we can't construct matrix before sampling.

My solution is: Discrete Value Iteration, but based on key-value storage. State-Action pair as key, value stored in Dict. 
So we can iterate Q-value while sampling.

Is this a good idea? I must solve this specific MDP.
Can I contribute this solver to this repository when I finished?

**Comment by NeroBlackstone** [comment]
I think opening a new repository for this solver is better.

**Comment by zsunberg** [comment]
Hi @NeroBlackstone , the value iteration algorithm is fundamentally tied to enumerating the entire state space (unless there is an unreachable part), so you are right that you should probably create this in a different repo. You may wish to have a look at chapter 9 of this book: https://algorithmsbook.com/#outline That contains some ideas related to what you are looking for.
